<?php
// api/db_connection.php

/**
 * Get database connection
 * 
 * Uses db_config.php generated by user-data at runtime with actual DB credentials
 * Falls back to default values if config file doesn't exist (for local testing)
 * 
 * @return PDO
 */
function getDatabaseConnection() {
    // Load runtime configuration if available (generated by user-data)
    $config_file = __DIR__ . '/db_config.php';
    if (file_exists($config_file)) {
        require_once $config_file;
        return get_db_connection_pdo();
    }
    
    // Fallback for local development
    $host = getenv('DB_HOST') ?: 'localhost';
    $db_name = getenv('DB_NAME') ?: 'demo_db';
    $username = getenv('DB_USER') ?: 'root';
    $password = getenv('DB_PASS') ?: '';
    
    $dsn = "mysql:host=$host;dbname=$db_name;charset=utf8mb4";
    $options = [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ];
    
    return new PDO($dsn, $username, $password, $options);
}

/**
 * Create PDO connection from config constants
 */
function get_db_connection_pdo() {
    if (!defined('DB_HOST')) {
        throw new Exception('DB configuration not loaded');
    }
    
    $dsn = "mysql:host=" . DB_HOST . ";dbname=" . DB_NAME . ";charset=utf8mb4;port=" . DB_PORT;
    $options = [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ];
    
    return new PDO($dsn, DB_USER, DB_PASS, $options);
}
?>